create database video1;
use video1;


SET
  NAMES utf8;
SET
  FOREIGN_KEY_CHECKS = 0;
-- ----------------------------
  -- Table structure for categories
  -- ----------------------------
  DROP TABLE IF EXISTS `videos`;
CREATE TABLE `videos` (
    `id` INT (11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `idvideo` VARCHAR (50) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
    `videosname` VARCHAR (254) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
    `datevideo` VARCHAR (50) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
    `dateexport` int(8),
    `like` float,
    `views` float,
    `idchannel` VARCHAR (50) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
    
    PRIMARY KEY (`id`) USING BTREE
  ) ENGINE = MYISAM AUTO_INCREMENT = 1 CHARACTER 
SET = UTF8 COLLATE = UTF8_UNICODE_CI;

  DROP TABLE IF EXISTS `playlist`;
CREATE TABLE `playlist` (
    `id` INT (11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `idplaylist` VARCHAR (50) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
    `playlistname` VARCHAR (254) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
    PRIMARY KEY (`id`) USING BTREE
  ) ENGINE = MYISAM AUTO_INCREMENT = 1 CHARACTER 
SET = UTF8 COLLATE = UTF8_UNICODE_CI;


  DROP TABLE IF EXISTS `channel`;
CREATE TABLE `channel` (
    `id` INT (11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `idchannel` VARCHAR (50) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
    `channelname` VARCHAR (254) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
    PRIMARY KEY (`id`) USING BTREE
  ) ENGINE = MYISAM AUTO_INCREMENT = 1 CHARACTER 
SET = UTF8 COLLATE = UTF8_UNICODE_CI;